/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/tags": {
    /** List Tags */
    get: operations["hako_api_list_tags"];
    /** Create Tag */
    post: operations["hako_api_create_tag"];
  };
  "/api/tags/{tag_id}": {
    /** Update Tag */
    put: operations["hako_api_update_tag"];
    /** Delete Tag */
    delete: operations["hako_api_delete_tag"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** TagOut */
    TagOut: {
      /** Id */
      id: number;
      /** Name */
      name: string;
    };
    /** TagIn */
    TagIn: {
      /** Name */
      name: string;
    };
    /** TagUpdateIn */
    TagUpdateIn: {
      /** Name */
      name: string;
      /** Category */
      category?: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {

  /** List Tags */
  hako_api_list_tags: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": (components["schemas"]["TagOut"])[];
        };
      };
    };
  };
  /** Create Tag */
  hako_api_create_tag: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["TagIn"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        content: {
          "application/json": components["schemas"]["TagOut"];
        };
      };
    };
  };
  /** Update Tag */
  hako_api_update_tag: {
    parameters: {
      path: {
        tag_id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TagUpdateIn"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["TagOut"];
        };
      };
    };
  };
  /** Delete Tag */
  hako_api_delete_tag: {
    parameters: {
      path: {
        tag_id: number;
      };
    };
    responses: {
      /** @description No Content */
      204: never;
    };
  };
}
